//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute_Of_Fine_Arts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_pro
    {
        public int s_id { get; set; }
        public string s_img { get; set; }
        public string s_firstname { get; set; }
        public string s_lastname { get; set; }
        public string s_class { get; set; }
        public string s_subject { get; set; }
        public Nullable<System.DateTime> s_sdate { get; set; }
        public Nullable<System.DateTime> s_edate { get; set; }
        public string s_remarks { get; set; }
    }
}
